### PR TITLE
Rename @genty_deferred to @genty_dataprovider

### PR DESCRIPTION
**Pull request by potrebic**
Finailize on the name "genty_provider" for the new mechanism of
generating the parameters to the test_methods as the test is invoked.

There not functionliaty change here, just lots of renaming of methods
and identifiers and docstring updates.

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @potrebic has signed the CLA. Thanks for the pull request!

**Comment by Jeff-Meadows** [comment]
Data provider is 2 words, so shouldn't this be genty_data_provider? Either way, the commit msg says genty_provider while the code says genty_dataprovider.

I think this is now confusing - we have genty_dataset and genty_dataprovider - I'm not sure that it's clear that one is for actual data and one is for data factories.

**Comment by potrebic** [comment]
The commit message in this PR says "genty_provider". The commit message on my local machine has been updated to say "genty_dataprovider", but I didn't push it waiting for other feedback.

"data set" is also 2 words, but combined here.

dataset - the data is "right there".
dataprovider - means the actual data will be provided by the function given to the dataprovider decorator.

But yes, anyone can in their heads think it's means something else. Just like POST vs PUT. Nomenclature. Kunal suggested "genty_dataprovider" and I liked it.

**Comment by potrebic** [comment]
Actually I did update the commit using "--force", so if you look at the actual commit it says "genty_dataprovider"... it's just the PR has the old wording. Very confusing.

**Pull request merged**
